sudo: required
services:
  - docker

before_install:
  - docker build -t msu/github-travisci-to-aws -f Dockerfile.dev .

script:
  - docker run msu/github-travisci-to-aws npm run test -- --coverage

#deploy:
#  provider: elasticbeanstalk
#  region: "us-west-2"
#  app: "docker"
#  env: "Docker-env"
#  bucket_name: "elasticbeanstalk-us-west-2-306476627547"
#  bucket_path: "docker"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: "$AWS_SECRET_KEY"

